version: '3.8'

services:
  playwright-tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VITE_STRIPE_PUBLIC_KEY=${VITE_STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    volumes:
      - ../test-results:/app/test-results
      - ../playwright-report:/app/playwright-report
    depends_on:
      - postgres
      - app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://testuser:testpass@postgres:5432/testdb
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - postgres